### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lt33a** [StexHub/EternityAPK#1]
how to i make this work? it needs some stub token and webhook id where can i get this?

**Comment by Benjjiyy** [comment]
can you read? he said he wouldnt help cause he isnt the creator

**Comment by lt33a** [comment]
lmao so he doesnt know how to use it? LOL

**Comment by Benjjiyy** [comment]
> lmao so he doesnt know how to use it? LOL

neither do you. i'm sure he knows how to use it, probably just doesn't bother answering all the skids asking for help

**Comment by Benjjiyy** [comment]
took me 1 minute to figure out what i had to do to make it work. shouldn't be so hard for you either.

**Comment by StexHub** [comment]
> > lmao so he doesnt know how to use it? LOL
> 
> neither do you. i'm sure he knows how to use it, probably just doesn't bother answering all the skids asking for help

exactly that, i don't like skids lmao

**Comment by StexHub** [comment]
if you want to use it, get a server or just learn to code and send it directly to a webhook without server requests

**Comment by lt33a** [comment]
> > lmao so he doesnt know how to use it? LOL
> 
> neither do you. i'm sure he knows how to use it, probably just doesn't bother answering all the skids asking for help

seems like he doesnt how to do it and neither do you

**Comment by Benjjiyy** [comment]
> > > lmao so he doesnt know how to use it? LOL
> > 
> > 
> > neither do you. i'm sure he knows how to use it, probably just doesn't bother answering all the skids asking for help
> 
> seems like he doesnt how to do it and neither do you

i already told you ik what needs to be done. Just get jd decompiler or sum shit and open it up then go the the mailclass and change what u gotta change, easy, dont be stupid
